//Website to generate ideas for things to do
//User clicks button (id = "bored-button")
//A random idea is generated
//The "ideas" are stored in an array
//let ideas = [];
//The "idea" generated by the computer is chosen:
//When button is clicked:
//Generate a random number
//Returns a random integer from 0 to 9
//Math.floor(Math.random()*10)
//let randomNumber = Math.floor(Math.random()*ideas.length)
//ideas[randomNumber];

//The big idea
let idea = "";

let ideaa2 = "";

//An array of ideas for what to do
let ideas = [
  "Organise your bookshelf",
  "Organise your CDs",
  "Play a game of chess",
  "Do some laundry",
  "Wash the dishes",
  "Clean the kitchen",
  "Change your bedding",
  "Tidy your room",
  "Practise on codewars",
  "Do a face mask",
  "Go for a walk",
  "Do 20 minutes on the elliptical",
  "Read a book",
  "Call a friend",
  "Play the piano",
  "Iron",
];

let ideaText = document.querySelector("#idea-text");

//An event listener to generate the random idea when you click the "#bored- button"
let boredButton = document.querySelector("#bored-button");
boredButton.addEventListener("click", generateIdea);

function generateIdea() {
  //A random number that will be used to generate a random idea
  let randomNumber = Math.floor(Math.random() * ideas.length);
  console.log(randomNumber);
  //Choose a random idea
  idea = ideas[randomNumber];
  ideaText.textContent = idea;
}

//Add a new idea
let textInputButton = document.querySelector("#text-input-button");

textInputButton.addEventListener("click", addNewIdea);

let count = 0;

let removeButton;

function addNewIdea() {
  let textInput = document.querySelector("#new-idea").value;
  ideas.push(textInput);
  let newLi = document.createElement("li");
  newLi.textContent = textInput;
  newLi.id = `new-idea${count}`;
  document.body.appendChild(newLi);
  removeButton = document.createElement("button");
  removeButton.textContent = "Remove";
  removeButton.id = `${count}`;
  removeButton.addEventListener("click", removeIdea);
  newLi.appendChild(removeButton);
  count++;
}

function removeIdea(event) {
  num = event.target.id;
  let ideaToRemove = document.querySelector(`#new-idea${num}`);
  ideaToRemove.remove();
}
